bot:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

modules:
  - changed-files:
      - any-glob-to-any-file:
          - "modules/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "build.gradle.kts"
          - "**/build.gradle.kts"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**.md"

workflow:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
