security:
    jwt:
        secret-key: ${JWT_KEY}
        token-duration: 1D  # TODO: Change to 1m
        refresh-token-duration: 7D

logging:
    level:
        org.springframework: debug

server:
    port: ${API_PORT}
