CREATE TABLE IF NOT EXISTS user_games (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    opponent1_id INT UNSIGNED NOT NULL,
    opponent2_id INT UNSIGNED NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winner_id INT UNSIGNED,
    game_type TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (opponent1_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (opponent2_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (winner_id) REFERENCES users(id) ON DELETE CASCADE
);
