name: Maven CI

on:
  push:
    branches:
      - master
      - integration
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Test with Maven
        run: mvn test
